### PR TITLE
PROTON-2147 on xcode10.1, openssl is in opt/openssl@11/, not in opt/openssl/

### PR DESCRIPTION
**Pull request by jdanekrh**
This is the minimal change that seems to resolve this.

I have another PR which uses the addons:homebrew:packages feature in .travis.yml, but making any larger change to dependencies on macOS seems to be a tarpit full of issues so far to me.

### CODE REVIEW

**Comment by jdanekrh** [comment]
Ok, merged. My fancier attempt at brew in travis is https://travis-ci.org/jdanekrh/qpid-proton/builds/617180027, https://github.com/apache/qpid-proton/compare/master...jdanekrh:jd_2019-11_macos_openssl?expand=1 (diff at the bottom). Currently fails on running `gem`, and is slow as I mentioned.

**Comment by jdanekrh** [comment]
@astitcher Master still failing in Travis. Afaik the issue was caused by https://github.com/apache/qpid-proton/commit/6be92fc56ea68187b9e36946790fe977db57809a this https://travis-ci.org/apache/qpid-proton/builds/617229924.

```
[ 23%] Linking C shared module cproton.so
CMakeFiles/cproton-ruby.dir/cprotonRUBY_wrap.c.o: In function `_wrap_pn_connection_error':
/home/travis/build/apache/qpid-proton/build/ruby/cprotonRUBY_wrap.c:7315: undefined reference to `pn_connection_error'
CMakeFiles/cproton-ruby.dir/cprotonRUBY_wrap.c.o: In function `_wrap_pn_session_error':
/home/travis/build/apache/qpid-proton/build/ruby/cprotonRUBY_wrap.c:8188: undefined reference to `pn_session_error'
CMakeFiles/cproton-ruby.dir/cprotonRUBY_wrap.c.o: In function `_wrap_pn_link_error':
/home/travis/build/apache/qpid-proton/build/ruby/cprotonRUBY_wrap.c:8838: undefined reference to `pn_link_error'
collect2: error: ld returned 1 exit status
ruby/CMakeFiles/cproton-ruby.dir/build.make:85: recipe for target 'ruby/cproton.so' failed
```
